# pylint: skip-file
# Generated by Django 4.2.1 on 2023-05-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(unique=True, verbose_name='title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modifed')),
                ('data', models.JSONField(null=True, verbose_name='data')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
