# pylint: skip-file
# Generated by Django 4.2.1 on 2023-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(verbose_name='title'),
        ),
    ]
