# pylint: skip-file
# Generated by Django 4.2.1 on 2023-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sharing',
            field=models.CharField(choices=[('PB', 'Public'), ('No', 'None')], default='No', max_length=12, verbose_name='sharing'),
        ),
    ]
